In [69]:
import pandas as pd

In [70]:
# read yaaas.csv
df = pd.read_csv("yaaas.csv")

# read network_nodes.csv
df_nodes = pd.read_csv("network_nodes.csv")

# read network_edges.csv
df_edges = pd.read_csv("network_edges.csv")

In [71]:
df.head()

,Id,Label,pageranks,modularity_class,indegree,outdegree,Degree,weighted indegree,weighted outdegree,Weighted Degree,...,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality,Authority,Hub,componentnumber,strongcompnum,stat_inf_class,clustering,eigencentrality
0,8500010,Basel SBB,0.000010,11,0,13,13,0,179568,179568,...,0.095904,0.132625,0.000000,0.0,0.0,0,3339,7,0.064103,0.000000
1,8500020,Muttenz,0.000013,11,1,2,3,43662,43930,87592,...,0.084055,0.105995,0.000000,0.0,0.0,0,3337,7,0.333333,0.001833
2,8500022,Frenkendorf-Füllinsdorf,0.000019,11,1,1,2,20739,20603,41342,...,0.083899,0.105156,2740.819048,0.0,0.0,0,3335,7,0.000000,0.004718
3,8500023,Liestal,0.000028,11,3,5,8,52469,52786,105255,...,0.091555,0.122041,9347.652381,0.0,0.0,0,3333,7,0.125000,0.008881
4,8500104,Court,0.000031,39,1,1,2,10333,10333,20666,...,0.077704,0.093437,7780.250000,0.0,0.0,0,3340,12,0.000000,0.003568

In [72]:
df_nodes.head()

,id,label,x_fa2,y_fa2,x_geo,y_geo,indegree,outdegree,degree,betweenness_centrality,transport_type,city,canton,is_bus_stop,is_tram_stop,is_train_stop,is_metro_stop,is_rack_railway_stop,is_boat_stop
0,8500010,Basel SBB,3224.670618,3971.930148,8747.787053,1083.724166,0.0,179568.0,179568.0,0.000000,Train,Basel,BS,False,False,True,False,False,False
1,8500016,Basel St. Johann,3197.918906,3963.147252,8740.453774,1098.214087,43662.0,43930.0,87592.0,0.000000,Train,Basel,BS,False,False,True,False,False,False
2,8500020,Muttenz,3214.033084,3969.759300,8772.829603,1075.023376,20739.0,20603.0,41342.0,2740.819048,Train,Muttenz,BL,False,False,True,False,False,False
3,8500021,Pratteln,3198.389545,3981.655233,8791.268213,1068.157330,52469.0,52786.0,105255.0,9347.652381,Train,Pratteln,BL,False,False,True,False,False,False
4,8500023,Liestal,3280.207836,3979.718988,8808.760961,1044.015059,10333.0,10333.0,20666.0,7780.250000,Train,Liestal,BL,False,False,True,False,False,False

In [73]:
# reaname columns by removing spaces and capital letters
df.columns = df.columns.str.replace(" ", "_").str.lower()
# drop label
df = df.drop(columns=['label'])

In [74]:
df.columns

Index(['id', 'pageranks', 'modularity_class', 'indegree', 'outdegree',
       'degree', 'weighted_indegree', 'weighted_outdegree', 'weighted_degree',
       'eccentricity', 'closnesscentrality', 'harmonicclosnesscentrality',
       'betweenesscentrality', 'authority', 'hub', 'componentnumber',
       'strongcompnum', 'stat_inf_class', 'clustering', 'eigencentrality'],
      dtype='object')

In [75]:
df_nodes.columns

Index(['id', 'label', 'x_fa2', 'y_fa2', 'x_geo', 'y_geo', 'indegree',
       'outdegree', 'degree', 'betweenness_centrality', 'transport_type',
       'city', 'canton', 'is_bus_stop', 'is_tram_stop', 'is_train_stop',
       'is_metro_stop', 'is_rack_railway_stop', 'is_boat_stop'],
      dtype='object')

In [76]:
# drop indegree outdegree degree from df_nodes
df_nodes = df_nodes.drop(columns=["indegree", "outdegree", "degree"])

In [77]:
# join df and df_nodes on id
df_nodes = df_nodes.join(df.set_index('id'), on='id')
df_nodes.head()

,id,label,x_fa2,y_fa2,x_geo,y_geo,betweenness_centrality,transport_type,city,canton,...,closnesscentrality,harmonicclosnesscentrality,betweenesscentrality,authority,hub,componentnumber,strongcompnum,stat_inf_class,clustering,eigencentrality
0,8500010,Basel SBB,3224.670618,3971.930148,8747.787053,1083.724166,0.000000,Train,Basel,BS,...,0.095904,0.132625,0.000000,0.0,0.0,0,3339,7,0.064103,0.000000
1,8500016,Basel St. Johann,3197.918906,3963.147252,8740.453774,1098.214087,0.000000,Train,Basel,BS,...,0.000000,0.000000,0.000000,0.0,0.0,0,3338,7,0.000000,0.001833
2,8500020,Muttenz,3214.033084,3969.759300,8772.829603,1075.023376,2740.819048,Train,Muttenz,BL,...,0.084055,0.105995,0.000000,0.0,0.0,0,3337,7,0.333333,0.001833
3,8500021,Pratteln,3198.389545,3981.655233,8791.268213,1068.157330,9347.652381,Train,Pratteln,BL,...,0.077602,0.094398,11.166667,0.0,0.0,0,3336,7,0.150000,0.004904
4,8500023,Liestal,3280.207836,3979.718988,8808.760961,1044.015059,7780.250000,Train,Liestal,BL,...,0.091555,0.122041,9347.652381,0.0,0.0,0,3333,7,0.125000,0.008881

In [ ]:
# save df_nodes to csv
df_nodes.to_csv("network_nodes.csv", index=False)